apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: prometheus-webhook
  name: prometheus-webhook
spec:
  selector:
    matchLabels:
      run: prometheus-webhook
  template:
    metadata:
      labels:
        run: prometheus-webhook
    spec:
      containers:
      - args:
        - --adapter=/app/prometheusalert/wx.js=/adapter/wx=https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=7f139aaa-bdda-4990-97ec-48559d3849c5
        image: registry.cn-shanghai.aliyuncs.com/c-things/webhook-adapter:v1.0.0 
        name: prometheus-webhook
        ports:
        - containerPort: 80
          protocol: TCP
 
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: prometheus-webhook
  name: prometheus-webhook
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: prometheus-webhook
  type: ClusterIP
